# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "%s | Codex"
og_image: /img/og.png
author: Codex
favicon: /img/favicon.ico
description: Codex is a durable, decentralised storage protocol designed to safeguard the world's most valuable information.
port: 8085

# OG image
origin: https://codex.storage
#og: /img/og.jpg

news:
  - title: Join testnet
    message: Codex is now in Alpha testing. Come help us build and test Codex.
    index: 01

  - title: Documentation
    message: View open-source documentation for the Codex Network.
    index: 02

navigation:
  header:
    - label: About
      href: /

    - label: Resources
      href: /

    - label: Vault
      href: /

    - label: Contributors
      href: /

    - label: FAQ
      href: /

    - label: Blog
      href: /

  header_social:
    - icon: icon/header/github.svg
      href: /
      label: Github
    - icon: icon/header/mastodon.svg
      href: /
      label: Discord

  footer:
    - About: /about
    - Clients: /
    - Getting Started: /
    - Resources: /
    - Community: /
    - Careers: /
    - Blog: /

  social:
    - label: Github
      href: /

    - label: Discord
      href: /

  end:
    - label: Terms & conditions
      link: /toto
    - label: Privacy Policy
      link: /
