# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: false
native_css_nesting: false
inline_css: true
sections: true

title_template: "%s | Codex"
og_image: /img/og.png
author: Codex
favicon: /img/favicon.ico
description: Codex is a durable, decentralised storage protocol designed to safeguard the world's most valuable information.
port: 8085

# OG image
origin: https://codex.storage
#og: /img/og.jpg
prefetch: [/img/hero.webp, /img/codex.mp4]
hero:
  video: /img/codex.mp4
  poster: /img/poster.jpg

app:
  version: 0.1.0

news:
  - title: Join testnet
    message: Codex is now in Alpha testing. Come help us build and test Codex.
    index: 01

  - title: Documentation
    message: View open-source documentation for the Codex Network.
    index: 02

navigation:
  header:
    - label: About
      href: "/#about"

    - label: Resources
      href: "/#resources"

    - label: Vault
      href: "/#ui"

    - label: Contributors
      href: "/#contributors"

    - label: FAQ
      href: "/#faq"

    - label: Blog
      href: "/#blog"

  header_social:
    - icon: icon/header/github.svg
      href: https://github.com/codex-storage/nim-codex
      label: Github
    - icon: icon/header/mastodon.svg
      href: https://discord.gg/codex-storage
      label: Discord

  footer:
    - About: "/#about"
    - Clients: /
    - Getting Started: https://docs.codex.storage
    - Resources: "/#resources"
    - Community: /
    - Careers: /
    - Blog: https://blog.codex.storage

  social:
    - label: Github
      href: https://github.com/codex-storage/nim-codex
      target: _blank

    - label: Discord
      href: https://discord.gg/codex-storage
      target: _blank

  end:
    - label: Terms & conditions
      link: /terms-and-conditions
    - label: Privacy Policy
      link: /privacy-policy
